services:
  ollama:
    image: ollama/ollama:latest
    container_name: adoptimizer-ai
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  api:
    image: gauravbanga/adoptimizer-backend:latest
    container_name: adoptimizer-backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/production.db
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_URL=http://ollama:11434
      - HOST=0.0.0.0
      - PORT=8080
      - GEMINI_API_KEY=AIzaSyDteYt195UOT4AMtuoBDLojfzy7R3VjyPc
    volumes:
      - db_data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped

  web:
    image: gauravbanga/adoptimizer-frontend:latest
    container_name: adoptimizer-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://172.105.36.248:8080
      - API_URL=http://api:8080
      - BACKEND_URL=http://api:8080
      - HOST=0.0.0.0
      - PORT=3000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  ollama_data:
  db_data:
