sonar.projectKey=SkillPulse-AiAdCampaignOptimizer
sonar.projectName=SkillPulse-AiAdCampaignOptimizer
sonar.sources=api/src,web/src
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
